doc: |
  Run benchmarks to evaluate AiSIO performance
  ============================================

  The benchmarks include:
  - reading 2 datasets: tiktokish, imagenetish (filesize8gib is skipped as
    individual files exceed the 256MB xNVMe uPCIe HOSTMEM heap limit),
  - performing synthetic randread benchmarks for: upcie, upcie-cuda

  See README.md for device binding and hugepage setup required before running
  this benchmark. This assumes you already ran 'setup_aisio.yaml' and
  'setup_dataset.yaml'.


steps:
- name: tiktokish
  uses: filperf
  with:
    backend: "aisio-cpu"
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 26
    batches: 1
    repetitions: 1

- name: imagenetish
  uses: filperf
  with:
    backend: "aisio-cpu"
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 1024
    batches: 300
    repetitions: 1

- name: upcie
  uses: xnvmeperf
  with:
    backend: "upcie"
    devices: ["{{ config.filesystems.dset.pci_addr }}"]
    runtime: 10
    iosize: 512
    iopattern: randread

- name: upcie-cuda
  uses: xnvmeperf
  with:
    backend: "upcie-cuda"
    devices: ["{{ config.filesystems.dset.pci_addr }}"]
    runtime: 10
    iosize: 512
    iopattern: randread
