doc: |
  Run the benchmarks using SPDK's bdevperf tool
  =============================================

  Configuration file
  ------------------
  See `configs/bench-amd.toml` for an example configuration file.

  You must change the `cijoe.transport.bench` key to have the correct remote hostname,
  username and path to a ssh key. If you run the cijoe script on same machine as the
  benchmarks, delete these fields completely.

  The configuration file must also define a list of NVMe block devices. To find these,
  run

    `lspci | grep Non-Volatile`

  and change the `pci_addr` keys in the `[[devices]]` to match the PCI addresses of the
  found devices.

  If the boot device is an NVMe device, see "Binding to userspace" below.

  Allocating hugepages
  --------------------
  It is not necessary to run this step if the workflow is run repeatedly.

  Binding to userspace
  --------------------
  This scripts assumes if the boot device is an NVMe device, then the `xnvme.driver.prefix`
  variable has been defined to add the device's PCIe address to the PCI_BLACKLIST env var
  for the xnvme-driver script. Example:

    [xnvme.driver]
    prefix = "PCI_BLACKLIST=0000:01:00.0"

  It's important that if the boot device is also an NVMe device that it's added in the
  `PCI_BLACKLIST` in step "bind_to_userspace", since the xnvme-driver script otherwise
  will unbind it, making the machine unusable (until next reboot).

  It is not necessary to run this step if the workflow is run repeatedly.

steps:
- name: allocate_hugepages
  run: |
    sysctl -w vm.nr_hugepages=1024
    mkdir -p /dev/hugepages
    mountpoint -q /dev/hugepages || mount -t hugetlbfs nodev /dev/hugepages

- name: bind_to_userspace
  run: |
    {{ config.xnvme.driver.prefix }} xnvme-driver

- name: run
  uses: bdevperf_runall
  with:
    depths: [64, 128, 256]
    sizes: [512, 4096]
    numcpus_range: [1, 8]
    numdevs_range: [1, 16]
    cpu_freqs: ["powersave", "performance", 3.0]
    turbo: [0,1]
    smt: [0,1]
    hyperthreads: [0,1]
    stress: [0,1]
    results_dir: &results-dir "{{ local.env.HOME }}/bench-results"

- name: combine
  uses: bdevperf_combine
  with:
    results_dir: *results-dir

- name: visualize
  uses: bdevperf_visualize
