doc: |
  Run benchmarks to evaluate AiSIO performance
  ============================================

  The benchmarks include:
  - reading 3 datasets: tiktokish, imagenetish, filesize8gib
  - performing synthetic randread benchmarks for: upcie, upcie-cuda

  See README.md for device binding and hugepage setup required before running
  this benchmark. This assumes you already ran 'setup_aisio.yaml' and
  'setup_dataset.yaml'.


steps:
- name: tiktokish
  uses: filperf
  with:
    backend: "aisio-cpu"
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 26
    batches: 1
    max_file_size: "{{ config.datasets.tiktokish.filesize_max }}"
    repetitions: 1

- name: tiktokish-gpu
  uses: filperf
  with:
    backend: "aisio-gpu"
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 26
    batches: 1
    max_file_size: "{{ config.datasets.tiktokish.filesize_max }}"
    gpu_nqueues: 4
    queue_depth: 512
    repetitions: 1

- name: imagenetish
  uses: filperf
  with:
    backend: "aisio-cpu"
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 1024
    batches: 300
    max_file_size: "{{ config.datasets.imagenetish.filesize_max }}"
    repetitions: 1

- name: imagenetish-gpu
  uses: filperf
  with:
    backend: "aisio-gpu"
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 1024
    batches: 300
    max_file_size: "{{ config.datasets.imagenetish.filesize_max }}"
    gpu_nqueues: 4
    queue_depth: 512
    repetitions: 1

- name: filesize8gib
  uses: filperf
  with:
    backend: "aisio-cpu"
    dataset: "filesize8gib"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 1
    batches: 10
    max_file_size: "{{ config.datasets.filesize8gib.filesize_max }}"
    repetitions: 1

- name: filesize8gib-gpu
  uses: filperf
  with:
    backend: "aisio-gpu"
    dataset: "filesize8gib"
    device: "{{ config.filesystems.dset.pci_addr }}"
    batch_size: 1
    batches: 10
    max_file_size: "{{ config.datasets.filesize8gib.filesize_max }}"
    gpu_nqueues: 4
    queue_depth: 512
    repetitions: 1

- name: cpu-initiated
  uses: xnvmeperf
  with:
    backend: "upcie"
    devices: ["{{ config.filesystems.dset.pci_addr }}"]
    runtime: 10
    iosize: 512
    qdepth: 128
    iopattern: randread

- name: p2p
  uses: xnvmeperf
  with:
    backend: "upcie-cuda"
    devices: ["{{ config.filesystems.dset.pci_addr }}"]
    runtime: 10
    iosize: 512
    qdepth: 128
    iopattern: randread

- name: dev-initiated
  uses: xnvmeperf
  with:
    command: "cuda-run"
    backend: "upcie-cuda"
    devices: ["{{ config.filesystems.dset.pci_addr }}"]
    nqueues: 1
    runtime: 10
    iosize: 512
    qdepth: 128
    iopattern: randread
