doc: |
  Run benchmarks to evaluate synthetic performance with GDS and AiSIO
  ===================================================================

  In this benchmark we are benchmarking random and sequential read using different tools:
  `gdsio` (GDS), `sil` (AiSIO)

  This assumes you already ran the task 'setup_aisio.yaml'
  

steps:
- name: benchmark_aisio_seq
  uses: sil
  with:
    backends: ["aisio"]
    dataset: ""
    device: "/dev/libnvm0"
    batch_size: 16777216
    random: false

- name: benchmark_aisio_rand
  uses: sil
  with:
    backends: ["aisio"]
    dataset: ""
    device: "/dev/libnvm0"
    batch_size: 16777216
    random: true

- name: benchmark_gdsio_seq
  uses: gdsio
  with:
    xfer_types: [0]
    mode: [0]

- name: benchmark_gdsio_rand
  uses: gdsio
  with:
    xfer_types: [0]
    mode: [2]
