doc: |
  Run I/O benchmarks for different tools
  ======================================

  Configuration file
  ------------------
  See `configs/devices_16.toml` for an example configuration file.

  The configuration file must also define a list of NVMe block devices. To find these,
  run

    `lspci | grep Non-Volatile`

  and change the `pci_addr` keys in the `[[devices]]` to match the PCI addresses of the
  found devices.

  If the boot device is an NVMe device, see "Binding to userspace" below.

  Allocating hugepages
  --------------------
  It is not necessary to run this step if the workflow is run repeatedly.

  Binding to userspace
  --------------------
  This scripts assumes if the boot device is an NVMe device, then the `xnvme.driver.prefix`
  variable has been defined to add the device's PCIe address to the PCI_BLACKLIST env var
  for the xnvme-driver script. Example:

    [xnvme.driver]
    prefix = "PCI_BLACKLIST=0000:01:00.0"

  It's important that if the boot device is also an NVMe device that it's added in the
  `PCI_BLACKLIST` in step "bind_to_userspace", since the xnvme-driver script otherwise
  will unbind it, making the machine unusable (until next reboot).

  It is not necessary to run this step if the workflow is run repeatedly.

steps:
- name: allocate_hugepages
  run: |
    sysctl -w vm.nr_hugepages=1024
    mkdir -p /dev/hugepages
    mountpoint -q /dev/hugepages || mount -t hugetlbfs nodev /dev/hugepages

- name: bind_to_userspace
  run: |
    {{ config.xnvme.driver.prefix }} xnvme-driver

- name: bdevperf
  uses: bench_runall
  with:
    depths: &qd [128]
    sizes: &io [512]
    numcpus_specific: &cpus [1]
    numdevs_specific: &devs [16]
    cpu_freqs: &cpufreq ["performance"]
    turbo: &turbo [1]
    smt: &smt [1]
    hyperthreads: &ht [1]
    stress: &stress [0]
    results_dir: &results-dir "{{ local.env.HOME }}/bench-tools-results"
    tool: bdevperf

- name: spdk_nvme_perf
  uses: bench_runall
  with:
    depths: *qd
    sizes: *io
    numcpus_specific: *cpus
    numdevs_specific: *devs
    cpu_freqs: *cpufreq
    turbo: *turbo
    smt: *smt
    hyperthreads: *ht
    stress: *stress
    results_dir: *results-dir
    tool: spdk_nvme_perf

- name: xnvmeperf_spdk
  uses: bench_runall
  with:
    depths: *qd
    sizes: *io
    numcpus_specific: *cpus
    numdevs_specific: *devs
    cpu_freqs: *cpufreq
    turbo: *turbo
    smt: *smt
    hyperthreads: *ht
    stress: *stress
    results_dir: *results-dir
    tool: xnvmeperf
    backend: spdk

- name: xnvmeperf_upcie
  uses: bench_runall
  with:
    depths: *qd
    sizes: *io
    numcpus_specific: *cpus
    numdevs_specific: *devs
    cpu_freqs: *cpufreq
    turbo: *turbo
    smt: *smt
    hyperthreads: *ht
    stress: *stress
    results_dir: *results-dir
    tool: xnvmeperf
    backend: upcie

- name: xnvmeperf_upcie_cuda
  uses: bench_runall
  with:
    depths: *qd
    sizes: *io
    numcpus_specific: *cpus
    numdevs_specific: *devs
    cpu_freqs: *cpufreq
    turbo: *turbo
    smt: *smt
    hyperthreads: *ht
    stress: *stress
    results_dir: *results-dir
    tool: xnvmeperf
    backend: upcie-cuda

- name: combine
  uses: bench_combine
  with:
    results_dir: *results-dir

- name: visualize
  uses: bench_visualize
  with:
    template: benchmark-tools
