doc: |
  Run SIL benchmarks to evaluate AiSIO performance
  ================================================

  The benchmark includes:
  - reading 3 different datasets: filesize8gib, tiktokish, imagenetish,
  - performing synthetic benchmarks for: read, rand-read

  This requires the device to be bound to `libnvm_helper`, which can be done in the following way:
  - Unmount if needed: `umount /mnt/datasets`
  - `cd /root/git/bam/builddir/module; make load`
  - `devbind --device '0000:01:00.0' --bind libnvm_helper`
  
  `device` should be adjusted to target the correct SSD.
  `batch_size` and `batches` are appropriate for a H100 GPU, and should be adjusted according to hardware.

  This assumes you already ran the tasks 'setup_aisio.yaml' and 'setup_dataset.yaml'


steps:
- name: filesize8gib
  uses: sil
  with:
    backends: ["aisio"]
    dataset: "filesize8gib"
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 1
    batches: 1

- name: tiktokish
  uses: sil
  with:
    backends: ["aisio"]
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 26
    batches: 1


- name: imagenetish
  uses: sil
  with:
    backends: ["aisio"]
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 4096
    batches: 300

- name: seqread
  uses: sil
  with:
    backends: ["aisio"]
    dataset: ""
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 16777216
    random: false

- name: randread
  uses: sil
  with:
    backends: ["aisio"]
    dataset: ""
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 16777216
    random: true
