doc: |
  Run SIL benchmarks to evaluate performance with different datasets
  ==================================================================

  In this benchmark we are reading 3 different datasets: filesize8gib, tiktokish, imagenetish
  with 3 different backends: POSIX, NVIDIA GDS, AiSIO

  `device` should be adjusted to target the correct SSD.
  `batch_size` and `batches` are appropriate for a H100 GPU, and should be adjusted according to hardware. 
  
  This assumes you already ran the tasks 'setup_aisio.yaml' and 'setup_datasets.yaml'
  

steps:
- name: benchmark_filesize8gib_aisio
  uses: sil
  with: 
    backends: ["aisio"]
    dataset: "filesize8gib"
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 1
    batches: 1

- name: benchmark_filesize8gib_posix_gds
  uses: sil
  with: 
    backends: ["posix", "gds"]
    dataset: "filesize8gib"
    device: "{{ config.filesystems.dset.bdev }}"
    batch_size: 1
    batches: 1

- name: benchmark_tiktokish_aisio
  uses: sil
  with: 
    backends: ["aisio"]
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.libnvm_dev }}"
    batch_size: 26
    batches: 1

- name: benchmark_tiktokish_posix_gds
  uses: sil
  with: 
    backends: ["posix", "gds"]
    dataset: "tiktokish"
    device: "{{ config.filesystems.dset.bdev }}"
    batch_size: 26
    batches: 1
  
- name: benchmark_imagenetish_aisio
  uses: sil
  with: 
    backends: ["aisio"]
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.libnvm }}"
    batch_size: 4096
    batches: 300

- name: benchmark_imagenetish_posix_gds
  uses: sil
  with: 
    backends: ["posix", "gds"]
    dataset: "imagenetish"
    device: "{{ config.filesystems.dset.bdev }}"
    batch_size: 4096
    batches: 300
