doc: |
  Evaluate NVIDIA GPU DirectStorage for 4K I/O using gdsio
  ========================================================

  This repeatedly runs gdsio with varied XferType, this is done to evaluate with API / GDS-use
  serves one best for small I/O. It is assumed that the system has been setup along the lines of:

    setup_nvstack.yaml.

  Also, with the storage-device setup according to:

    setup_dataset.yaml

  To run this workflow, invoke:

    cijoe \
      -c configs/transport.toml \
      -c configs/datasets.toml \
      tasks/compare_gds_xfermodes.yaml \
      --monitor

steps:
- name: check
  run: |
    hostname
    /usr/local/cuda/gds/tools/gdscheck -p
    nvidia-smi -q
    nvcc --version    
    dmesg | grep -i nvidia_fs
    lsmod | grep nvidia_fs
  
- name: run
  uses: gdsio
  with:
    mp: "{{ config.filesystems.dset.mountpoint }}/gds"
