doc: |
  Setup benchmark server and install dependencies

steps:
- name: dependencies
  run: |
    apt-get update
    apt-get -y install build-essential git htop linux-cpupower sysstat stress-ng time

- name: mkdir_git
  run: |
    mkdir -p {{ local.env.HOME }}/git

- name: fetch_sources
  uses: core.repository_prep

- name: xnvme_install
  run: |
    cd "{{ config.xnvme.repository.path }}"; chmod +x ./toolbox/pkgs/{{ config.os.name }}-{{ config.os.version }}.sh
    cd "{{ config.xnvme.repository.path }}"; ./toolbox/pkgs/{{ config.os.name }}-{{ config.os.version }}.sh
    cd "{{ config.xnvme.repository.path }}"; make config build install

- name: fio_install
  run: |
    cd "{{ config.fio.repository.path }}"; ./configure
    cd "{{ config.fio.repository.path }}"; make
    cd "{{ config.fio.repository.path }}"; make install

- name: spdk_install
  run: |
    cd "{{ config.spdk.repository.path }}"; ./scripts/pkgdep.sh
    cd "{{ config.spdk.repository.path }}"; ./configure --disable-unit-tests --disable-tests --enable-lto --with-fio="{{ config.fio.repository.path }}" --without-crypto --without-idxd --without-iscsi-initiator --without-nvme-cuse --without-ocf --without-rbd --without-uring --without-usdt --without-vfio-user --without-vhost --without-virtio --without-vtune --without-xnvme
    cd "{{ config.spdk.repository.path }}"; make -j$(nproc)
