doc: |
  Install Custom Kernel with UDMABUF import patches
  =================================================

  This adds dma-buf importer functionality to UDMABUF and the ability to share
  physical addresses, from the dma-buf, with userspace.

  The patch is added untop of the source of the kernel included with Ubuntu.
  This ensures compatibility with the other parts of the AiSIO stack that
  depends on the Linux kernel.

  This can be run with::

    cijoe --monitor \
      -c configs/transport.toml \
      -c configs/udmabuf_import.toml \
      tasks/setup_udmabuf_import.yaml

  Adjust transport.toml with the hostname and ssh-login info of the root user.
  Adjust udmabuf_import.toml with the path to your aisio github repository on the host.

steps:
- name: fetch_sources
  uses: core.repository_prep

- name: install_dependencies
  run: |
    apt-get -fy install bison build-essential debhelper-compat flex libelf-dev libncurses-dev libpci-dev libssl-dev

- name: fetch_kernel_source
  run: |
    apt-get -fy install {{ config.linux.source.pkg }}

- name: decompress_source
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; tar -jxf {{ config.linux.source.pkg }}.tar.bz2  --strip-components=1

- name: copy_patch
  run: |
    cp {{ config.udmabuf.repository.path }}/patches/{{ config.udmabuf.patch.name }} /usr/src/{{ config.linux.source.pkg }}

- name: apply_patch
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; git apply --reject {{ config.udmabuf.patch.name }}

- name: get_config
  run: |
    cp /boot/config-$(uname -r) /usr/src/{{ config.linux.source.pkg }}/.config

- name: configure
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --disable DEBUG_INFO
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --set-str SYSTEM_TRUSTED_KEYS ""
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --set-str SYSTEM_REVOCATION_KEYS ""
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --disable MODULE_SIG
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --disable MODULE_SIG
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable X86_AMD_PSTATE
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable ACPI_CPPC_LIB
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable X86_ACPI_CPUFREQ
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ_GOV_PERFORMANCE
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ_GOV_POWERSAVE
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ_GOV_USERSPACE
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ_GOV_ONDEMAND
    cd /usr/src/{{ config.linux.source.pkg }}; scripts/config --enable CPU_FREQ_GOV_SCHEDUTIL

- name: prepare
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; make olddefconfig scripts prepare modules_prepare

- name: build
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; make -j $(nproc) bindeb-pkg LOCALVERSION=-dmabuf

- name: install
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; dpkg -i ../*.deb

- name: reboot
  run: shutdown -r now

- name: wait_down
  uses: core.wait_for_transport
  with:
    state: down
    timeout: 60

- name: wait_up
  uses: core.wait_for_transport
  with:
    state: up
    timeout: 300

- name: install_cpupower
  run: |
    cd /usr/src/{{ config.linux.source.pkg }}; make tools/cpupower_install prefix=/usr libdir=/usr/lib
