doc: |
  AiSIO PoC Setup using the NVIDIA Software-Stack
  ===============================================

  Assuming you installed the system along the lines of the 'setup_nvstack.yaml'.

  With the above in place then run this workflow e.g.

    cijoe --monitor \
      -c configs/transport.toml \
      -c configs/aisio.toml \
      tasks/setup_aisio.yaml

  Adjusting transport.toml with the hostname and ssh-login info of the root user.

steps:
- name: fetch_sources
  uses: core.repository_prep

- name: python_tools
  run: |
    pipx install devbind
    pipx install hugepages
    pipx ensurepath

- name: gcc
  run: |
    apt-get -fy install gcc-12 g++-12
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 --slave /usr/bin/g++ g++ /usr/bin/g++-12
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 --slave /usr/bin/g++ g++ /usr/bin/g++-13
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 120 --slave /usr/bin/g++ g++ /usr/bin/g++-12
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 --slave /usr/bin/g++ g++ /usr/bin/g++-13
    update-alternatives --set gcc /usr/bin/gcc-12
    gcc --version
    g++ --version

- name: xnvme
  run: |
    chmod +x "{{ config.xnvme.repository.path }}/toolbox/pkgs/{{ config.os.distro }}-{{ config.os.version }}.sh"
    cd "{{ config.xnvme.repository.path }}"; ./toolbox/pkgs/{{ config.os.distro }}-{{ config.os.version }}.sh
    rm -r "{{ config.xnvme.repository.path }}/builddir" || true
    mkdir -p "{{ config.xnvme.repository.path }}/builddir"
    cd "{{ config.xnvme.repository.path }}"; meson setup builddir
    cd "{{ config.xnvme.repository.path }}"; meson install -C builddir

- name: xal
  run: |
    apt-get install -fy xfslibs-dev
    rm -r "{{ config.xal.repository.path }}/builddir" || true
    mkdir -p "{{ config.xal.repository.path }}/builddir"
    cd "{{ config.xal.repository.path }}"; meson setup builddir
    cd "{{ config.xal.repository.path }}"; meson install -C builddir

- name: sil
  run: |
    rm -r "{{ config.sil.repository.path }}/builddir" || true
    mkdir -p "{{ config.sil.repository.path }}/builddir"
    cd "{{ config.sil.repository.path }}"; meson setup builddir
    cd "{{ config.sil.repository.path }}"; meson install -C builddir

- name: fio
  run: |
    cd "{{ config.fio.repository.path }}"; ./configure; make; make install

- name: spdk
  run: |
    cd "{{ config.spdk.repository.path }}"; ./scripts/pkgdep.sh
    cd "{{ config.spdk.repository.path }}"; ./configure --disable-unit-tests --disable-tests --enable-lto --with-fio="{{ config.fio.repository.path }}" --without-crypto --without-idxd --without-iscsi-initiator --without-nvme-cuse --without-ocf --without-rbd --without-uring --without-usdt --without-vfio-user --without-vhost --without-virtio --without-vtune --without-xnvme
    cd "{{ config.spdk.repository.path }}"; make -j $(nproc)
