[os]
distro = "ubuntu"
version = "noble"

[xnvme.repository]
remote = "https://github.com/xnvme/xnvme"
branch = "next"
path = "/root/git/xnvme"

[xal.repository]
remote = "https://github.com/xnvme/xal"
tag = "v0.2.0"
path = "/root/git/xal"

[fil.repository]
remote = "https://github.com/xnvme/fil"
tag = "v0.2.1"
path = "/root/git/fil"

[spdk.repository]
remote = "https://github.com/spdk/spdk"
tag = "v26.01"
path = "/root/git/spdk"

[fio.repository]
remote = "https://github.com/axboe/fio"
tag = "fio-3.41"
path = "/root/git/fio"
