[cijoe.workflow]
fail_fast=true

[os]
name = "ubuntu"
version = "24.04"

[spdk.repository]
remote = "https://github.com/spdk/spdk"
tag = "v25.09"
path = "/root/git/spdk"

[xnvme.repository]
remote = "https://github.com/xnvme/xnvme"
tag = "v0.7.5"
path = "/root/git/xnvme"
